displayName=Barracuda Ghost Ship
author=Cytofusion
description=A RuneLite plugin that allows the user to record and playback Barracuda Trial runs as a ghost racers to be shared or raced against.
tags=sailing,ghost,replay,trial
plugins=com.barracudaghost.BarracudaGhostPlugin
version=
build=standard